spring.application.name=EcommerceApi
spring.jackson.deserialization.fail-on-null-for-primitives=false

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Poiuytrewq08!

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=eW91ci12ZXJ5LXN0cm9uZy1zZWNyZXQta2V5LXRoYXQtaXMtYXQtbGVhc3QtMzItY2hhcmFjdGVycy1sb25nLWZvci1oczI1Ng==
jwt.expiration=86400000
